/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InformesIndexRouteImport } from './routes/informes/index'
import { Route as ExpedientesIndexRouteImport } from './routes/expedientes/index'
import { Route as ExpedientesNuevoRouteImport } from './routes/expedientes/nuevo'
import { Route as ExpedientesExpedienteIdIndexRouteImport } from './routes/expedientes/$expedienteId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesIndexRoute = InformesIndexRouteImport.update({
  id: '/informes/',
  path: '/informes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIndexRoute = ExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesNuevoRoute = ExpedientesNuevoRouteImport.update({
  id: '/expedientes/nuevo',
  path: '/expedientes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesExpedienteIdIndexRoute =
  ExpedientesExpedienteIdIndexRouteImport.update({
    id: '/expedientes/$expedienteId/',
    path: '/expedientes/$expedienteId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/informes/': typeof InformesIndexRoute
  '/expedientes/$expedienteId/': typeof ExpedientesExpedienteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/expedientes': typeof ExpedientesIndexRoute
  '/informes': typeof InformesIndexRoute
  '/expedientes/$expedienteId': typeof ExpedientesExpedienteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expedientes/nuevo': typeof ExpedientesNuevoRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/informes/': typeof InformesIndexRoute
  '/expedientes/$expedienteId/': typeof ExpedientesExpedienteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expedientes/nuevo'
    | '/expedientes/'
    | '/informes/'
    | '/expedientes/$expedienteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expedientes/nuevo'
    | '/expedientes'
    | '/informes'
    | '/expedientes/$expedienteId'
  id:
    | '__root__'
    | '/'
    | '/expedientes/nuevo'
    | '/expedientes/'
    | '/informes/'
    | '/expedientes/$expedienteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpedientesNuevoRoute: typeof ExpedientesNuevoRoute
  ExpedientesIndexRoute: typeof ExpedientesIndexRoute
  InformesIndexRoute: typeof InformesIndexRoute
  ExpedientesExpedienteIdIndexRoute: typeof ExpedientesExpedienteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes/': {
      id: '/informes/'
      path: '/informes'
      fullPath: '/informes/'
      preLoaderRoute: typeof InformesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/': {
      id: '/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ExpedientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/nuevo': {
      id: '/expedientes/nuevo'
      path: '/expedientes/nuevo'
      fullPath: '/expedientes/nuevo'
      preLoaderRoute: typeof ExpedientesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/$expedienteId/': {
      id: '/expedientes/$expedienteId/'
      path: '/expedientes/$expedienteId'
      fullPath: '/expedientes/$expedienteId/'
      preLoaderRoute: typeof ExpedientesExpedienteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpedientesNuevoRoute: ExpedientesNuevoRoute,
  ExpedientesIndexRoute: ExpedientesIndexRoute,
  InformesIndexRoute: InformesIndexRoute,
  ExpedientesExpedienteIdIndexRoute: ExpedientesExpedienteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
